import type { Metadata } from "next";
import { Geist, Geist_Mono, DM_Serif_Text, Poppins} from "next/font/google";
import "./globals.css";
import Header from "@/components/shared/header";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const dmSerifText = DM_Serif_Text({
  variable: "--font-dm-serif-text",
  subsets: ["latin"],
  weight: "400",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets:["latin"],
  weight:"200"
})



export const metadata: Metadata = {
  title: "Boluwatife",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${dmSerifText.variable} ${poppins.variable} antialiased`}
      >
        <Header/>
        {children}
      </body>
    </html>
  );
}
